# Generated by Django 6.0.7 on 2026-08-20 01:52

import functools
import karrio.server.core.fields
import karrio.server.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_add_shipment_recipient_updated_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="enabled_events",
            field=karrio.server.core.fields.MultiChoiceField(
                choices=[
                    ("all", "all"),
                    ("shipment_purchased", "shipment_purchased"),
                    ("shipment_cancelled", "shipment_cancelled"),
                    ("shipment_fulfilled", "shipment_fulfilled"),
                    ("shipment_out_for_delivery", "shipment_out_for_delivery"),
                    ("shipment_delivered", "shipment_delivered"),
                    ("shipment_needs_attention", "shipment_needs_attention"),
                    ("shipment_delivery_failed", "shipment_delivery_failed"),
                    ("shipment_recipient_updated", "shipment_recipient_updated"),
                    ("tracker_created", "tracker_created"),
                    ("tracker_updated", "tracker_updated"),
                    ("pickup_scheduled", "pickup_scheduled"),
                    ("pickup_cancelled", "pickup_cancelled"),
                    ("pickup_closed", "pickup_closed"),
                    ("order_created", "order_created"),
                    ("order_updated", "order_updated"),
                    ("order_fulfilled", "order_fulfilled"),
                    ("order_cancelled", "order_cancelled"),
                    ("order_delivered", "order_delivered"),
                    ("batch_queued", "batch_queued"),
                    ("batch_failed", "batch_failed"),
                    ("batch_running", "batch_running"),
                    ("batch_completed", "batch_completed"),
                ],
                default=functools.partial(
                    karrio.server.core.models._identity, value=[]
                ),
                help_text="Webhook events",
            ),
        ),
    ]
